package com.mechanicel.tomsdarts.data

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import com.mechanicel.tomsdarts.data.dao.PlayerDao
import com.mechanicel.tomsdarts.data.entity.Player
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * Edge-Case-, Fehlerpfad- und Regressionstests fuer den Room-/Player-Stack.
 *
 * Gleiches Setup wie [PlayerDaoTest]: host-seitig (JVM) unter Robolectric mit
 * In-Memory-Room, Test-SDK auf 34 gepinnt (Robolectric unterstuetzt compileSdk
 * 36 noch nicht). Alle Tests sind deterministisch und benoetigen kein Geraet.
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class PlayerDaoEdgeCaseTest {

    private lateinit var db: TomsDartsDatabase
    private lateinit var dao: PlayerDao

    @Before
    fun createDb() {
        db = Room.inMemoryDatabaseBuilder(
            ApplicationProvider.getApplicationContext(),
            TomsDartsDatabase::class.java,
        ).build()
        dao = db.playerDao()
    }

    @After
    fun closeDb() {
        db.close()
    }

    // --- insert: generierte Row-IDs -----------------------------------------

    @Test
    fun insertReturnsPositiveGeneratedId() = runBlocking {
        val id = dao.insert(Player(name = "Tom", createdAt = 1_000L))

        assertTrue("Generierte Row-ID muss positiv sein, war $id", id > 0L)
    }

    @Test
    fun consecutiveInsertsProduceDistinctIds() = runBlocking {
        val id1 = dao.insert(Player(name = "A", createdAt = 1L))
        val id2 = dao.insert(Player(name = "B", createdAt = 2L))
        val id3 = dao.insert(Player(name = "C", createdAt = 3L))

        assertNotEquals(id1, id2)
        assertNotEquals(id2, id3)
        assertNotEquals(id1, id3)
        assertEquals(3, dao.getAll().size)
    }

    @Test
    fun insertWithDefaultIdZeroGetsAutoGeneratedId() = runBlocking {
        // id = 0 (Default) signalisiert Room "autogenerieren".
        val id = dao.insert(Player(name = "Auto", createdAt = 42L))

        assertNotEquals(0L, id)
        val persisted = dao.getById(id)
        assertEquals(id, persisted!!.id)
    }

    // --- getById: Fehlerpfad ------------------------------------------------

    @Test
    fun getByIdReturnsNullForNonexistentId() = runBlocking {
        assertNull(dao.getById(999L))
    }

    @Test
    fun getByIdReturnsNullOnEmptyDb() = runBlocking {
        assertNull(dao.getById(1L))
    }

    // --- getAll: leere DB / Mehrfach-Inserts --------------------------------

    @Test
    fun getAllReturnsEmptyListOnEmptyDb() = runBlocking {
        val all = dao.getAll()

        assertTrue("Leere DB muss leere Liste liefern", all.isEmpty())
    }

    @Test
    fun getAllReturnsAllInsertedPlayersOrderedById() = runBlocking {
        val id1 = dao.insert(Player(name = "Anna", createdAt = 10L))
        val id2 = dao.insert(Player(name = "Bert", createdAt = 20L))
        val id3 = dao.insert(Player(name = "Cleo", createdAt = 30L))

        val all = dao.getAll()

        assertEquals(3, all.size)
        // Query sortiert ORDER BY id -> Einfuegereihenfolge.
        assertEquals(listOf(id1, id2, id3), all.map { it.id })
        assertEquals(listOf("Anna", "Bert", "Cleo"), all.map { it.name })
    }

    @Test
    fun getAllContentsMatchInsertedPlayers() = runBlocking {
        dao.insert(Player(name = "Anna", createdAt = 10L))
        dao.insert(Player(name = "Bert", createdAt = 20L))

        val all = dao.getAll()

        assertEquals(setOf("Anna", "Bert"), all.map { it.name }.toSet())
        assertEquals(setOf(10L, 20L), all.map { it.createdAt }.toSet())
    }

    // --- onConflict = REPLACE -----------------------------------------------

    @Test
    fun insertWithExistingIdReplacesRowWithoutDuplicate() = runBlocking {
        val id = dao.insert(Player(name = "Original", createdAt = 100L))

        // Gleiche id erneut einfuegen -> REPLACE statt Duplikat.
        val replacedId = dao.insert(Player(id = id, name = "Geaendert", createdAt = 200L))

        assertEquals(id, replacedId)
        val all = dao.getAll()
        assertEquals("Kein Duplikat erwartet", 1, all.size)
        assertEquals("Geaendert", all.first().name)
        assertEquals(200L, all.first().createdAt)
    }

    @Test
    fun replaceUpdatesFieldsReadBackById() = runBlocking {
        val id = dao.insert(Player(name = "Alt", createdAt = 1L))

        dao.insert(Player(id = id, name = "Neu", createdAt = 999L))

        val reloaded = dao.getById(id)!!
        assertEquals("Neu", reloaded.name)
        assertEquals(999L, reloaded.createdAt)
    }

    // --- Feld-Persistenz / Randwerte ----------------------------------------

    @Test
    fun persistsEmptyName() = runBlocking {
        val id = dao.insert(Player(name = "", createdAt = 5L))

        assertEquals("", dao.getById(id)!!.name)
    }

    @Test
    fun persistsCreatedAtZero() = runBlocking {
        val id = dao.insert(Player(name = "Null-Zeit", createdAt = 0L))

        assertEquals(0L, dao.getById(id)!!.createdAt)
    }

    @Test
    fun persistsLargeCreatedAt() = runBlocking {
        val id = dao.insert(Player(name = "Max", createdAt = Long.MAX_VALUE))

        assertEquals(Long.MAX_VALUE, dao.getById(id)!!.createdAt)
    }

    @Test
    fun persistsNegativeCreatedAt() = runBlocking {
        // Vor Epoch (1970) -> negativer Epoch-Millis-Wert muss erhalten bleiben.
        val id = dao.insert(Player(name = "Vergangenheit", createdAt = -1_000L))

        assertEquals(-1_000L, dao.getById(id)!!.createdAt)
    }

    @Test
    fun persistsUnicodeAndWhitespaceName() = runBlocking {
        val name = "  Tom 🎯 äöü  "
        val id = dao.insert(Player(name = name, createdAt = 1L))

        assertEquals(name, dao.getById(id)!!.name)
    }
}
